spring.application.name=central-config
server.port=${PORT_CENTRAL_CONFIG}

# config declarative
spring.cloud.config.server.default-label=main
spring.cloud.config.server.git.uri=https://github.com/IrisDuong/vcfon.git
spring.cloud.config.server.git.search-paths=central-config-repo
spring.cloud.config.server.git.clone-on-start=true