server.port=${PORT_GATEWAY}

# oauth2 login
spring.security.oauth2.client.registration.gateway-client.client-id=${sec.oauth2.gateway.client-id}
spring.security.oauth2.client.registration.gateway-client.client-secret=${sec.oauth2.gateway.client-secret}
spring.security.oauth2.client.registration.gateway-client.scope=openid,profile,email
spring.security.oauth2.client.registration.gateway-client.redirect-uri=${url.gateway}/login/oauth2/code/${sec.oauth2.gateway.client-id}
spring.security.oauth2.client.registration.gateway-client.provider=auth-server
spring.security.oauth2.client.registration.gateway-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.auth-server.issuer-uri=${url.auth-server}