management.endpoints.web.exposure.include=health,info

# urls
url.gateway=${MAIN_HOST}:${PORT_GATEWAY}
url.auth-server=${MAIN_HOST}:${PORT_AUTH_SERVER}
url.front-end=${MAIN_HOST}:${PORT_FE}

# connect to discovery server
eureka.client.service-url.defaultZone=${MAIN_HOST}:${PORT_DISCOVERY}/eureka/
eureka.instance.prefer-ip-address=true

# security oauth2 client registration
sec.oauth2.google.client-id=${GOOGLE_CLIENT_ID}
sec.oauth2.google.client-secret=${GOOGLE_CLIENT_SECRET}
sec.oauth2.gateway.client-id=${GATEWAY_CLIENT_ID}
sec.oauth2.gateway.client-secret=${GATEWAY_CLIENT_SECRET}