server.port=${PORT_AUTH_SERVER}

# oauth2 login
spring.security.oauth2.client.registration.google.client-id=${sec.oauth2.google.client-id}
spring.security.oauth2.client.registration.google.client-secret=${sec.oauth2.google.client-secret}
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${url.auth-server}/login/oauth2/code/google